
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  // Migrasi/push memerlukan koneksi langsung (session pooler port 5432).
  // Pooler transaksi (6543) tidak kompatibel dengan prepared statement.
  datasource: {
    url: env("DIRECT_URL"),
  },
});
